name: 'Check directory permission 2'
description: 'Action that allows to check PR if all edited files are permitted to edit by CODEOWNERS config'
inputs:
  GITHUB_TOKEN:
    description: 'Github token'
    required: true
#  who-to-greet:  # id of input
#    description: 'Who to greet'
#    required: true
#    default: 'World'
#outputs:
#  time: # id of output
#    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'